# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68600c19561b7e6d52881ae3fa414033c7b10a889e5c4af244ffcd5e7cdf31401616b0f4135a957a97be5c37b17c861235bac9409bec1a161ae1e4a47164f6ed

test:
  secret_key_base: 13828869f1c63c5520dbdf36cd0d942cb48d6c2058b530bae6c8229f10df4600855aec172568ed59e35cf347c38f01083aeb037ba1a667de75353efb53e8c912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
